### PR TITLE
Define CommonJS and ES module entry points

### PR DESCRIPTION
**Pull request by lij20**
Fix for issue #13

### CODE REVIEW

**Comment by zhangHongEn** [comment]
If you use require in a webpack built browser project, it should not automatically reference dist/node, otherwise an error will occur

**Comment by lij20** [comment]
Webpack still tries to reference the ES module even when I use the require syntax.
```js
const { registerRemotes, findModule } = require("module-federation-runtime")

// get a SyntaxError: Unexpected token 'export' error from <my-app>/node_modules/module-federation-runtime/dist/index.js:1
```

The only way I've been able to get it to use the CJS module has been to point to the dist/node/index.js directly, but that raises the warnings in #13. 

I don't think Webpack knows where to find the CJS module because the file is missing the `.cjs` file extension, and the `main` and `module` properties in the `package.json` both point to the same file (the ES module). 

This PR should fix that though.

**Comment by zhangHongEn** [comment]
your project should use dist/umd instead of dist/node. You can modify the pr to point the main field to dist/umd

**Comment by lij20** [comment]
Gotcha! I updated the PR, please take a look when you have a moment.

**Comment by zhangHongEn** [comment]
the "exports" field causes webpack to introduce two different files using "import" and "require", resulting in a larger build output, which is inappropriate. In webpack, both import and require should prioritize using the es module to support tree sharing, regardless of the nodejs version

If you are using it in an environment that does not support ES at all, you do not need to modify the exports field, only the main field

**Comment by lij20** [comment]
Specifying different entry points in the exports field does not increase the build output. It just defines a mapping of files that are already part of the package to different entry points. 

The official docs on the nodejs website states that the exports field is a modern alternative to the main and module fields, and [even recommends using the "exports" field](https://nodejs.org/api/packages.html#package-entry-points). 

> For new packages targeting the currently supported versions of Node.js, the ["exports"](https://nodejs.org/api/packages.html#exports) field is recommended. For packages supporting Node.js 10 and below, the ["main"](https://nodejs.org/api/packages.html#main) field is required. If both ["exports"](https://nodejs.org/api/packages.html#exports) and ["main"](https://nodejs.org/api/packages.html#main) are defined, the ["exports"](https://nodejs.org/api/packages.html#exports) field takes precedence over ["main"](https://nodejs.org/api/packages.html#main) in supported versions of Node.js.

Anyways, I updated the PR to remove the exports field, but personally I suggest adding it in.

**Comment by zhangHongEn** [comment]
image
theoretically, the build will become larger. This is true when I tried it.

**Pull request merged**
